### ISSUE TITLE
error.php redirects fail in joomla 3.6.2, solution included.

### ISSUE THREAD

**Issue by vdrover** [ghazal/plg_mvcoverride#17]
On joomla 3.6.2 and possibly other versions, the error.php redirects to custom 404 pages does not  work properly. For example, this URL, if not found, redirects normally to the url specified in error.php

article-name.html

this url does not redirect properly:

news/article-name.html

instead, you get a query error related to line 52 of mvcoverride.php:

`$db->setQuery('SELECT * FROM #__extensions WHERE id ='.$db->quote($componentID));`

shoudl eb this instead:

`$db->setQuery('SELECT * FROM #__extensions WHERE extension_id ='.$db->quote($componentID));`

**Comment by ghazal** [comment]
Corrected.
TKS.

**Comment by vdrover** [comment]
I have another bug to report, but it's a little complicated to explain and
I don't have a solution. Could I send you details and an Akeeba back where
you can see it in action?

Cheers,

Victor Drover
Founder and CEO, Anything Digital <https://mail.google.com/>
Co-founder, Watchful.li <https://watchful.li/> & jInbound.com
<http://jinbound.com/>
262-923-8200 ext. 0
Facebook: AnythingDigital <https://www.facebook.com/AnythingDigital> |
watchfulli <https://www.facebook.com/watchfulli> | JInbound
<https://www.facebook.com/JInbound>
Twitter: @VicDrover <https://twitter.com/VicDrover> | @AnythingDig
<https://twitter.com/AnythingDig> | @watchfulli
<https://twitter.com/watchfulli> | @JoomlaInbound
<https://twitter.com/joomlainbound>

**Comment by ghazal** [comment]
OK. Post it in your repo section of plg_mvcoverride. I'll go get it.
